/**
 * Created by imaslov on 06.02.17.
 */
var project1 = {
    "tasks": [
        {
            "id": -1,
            "name": "Диаграмма Ганта",
            "progress": 0,
            "description": "",
            "code": "",
            "level": 0,
            "status": "STATUS_SUSPENDED",
            "depends": "",
            "canWrite": true,
            "start": 1485464400000,
            "duration": 114,
            "end": 1499720399999,
            "startIsMilestone": true,
            "endIsMilestone": false,
            "collapsed": false,
            "assigs": [],
            "hasChild": true
        },
        {
            "id": "tmp_fk1486366951382",
            "name": "Разработка и утверждение НПА по проектному управлению",
            "progress": 0,
            "description": "",
            "code": "",
            "level": 1,
            "status": "STATUS_SUSPENDED",
            "depends": "",
            "canWrite": true,
            "start": 1485464400000,
            "duration": 78,
            "end": 1495141199999,
            "startIsMilestone": false,
            "endIsMilestone": false,
            "assigs": [],
            "hasChild": true
        },
        {
            "id": "tmp_fk1486366461612",
            "name": "Провести предварительную диагностику систему управления проектами в ЛО",
            "progress": 0,
            "description": "",
            "code": "",
            "level": 2,
            "status": "STATUS_SUSPENDED",
            "depends": "",
            "canWrite": true,
            "start": 1485464400000,
            "duration": 15,
            "end": 1487278799999,
            "startIsMilestone": false,
            "endIsMilestone": false,
            "assigs": [],
            "hasChild": false
        },
        {
            "id": "tmp_fk1486366512252",
            "name": "Провести конкурс на консалтинг по внедрению систем проектного управления в ЛО",
            "progress": 0,
            "description": "",
            "code": "",
            "level": 2,
            "status": "STATUS_SUSPENDED",
            "depends": "",
            "canWrite": true,
            "start": 1485464400000,
            "duration": 20,
            "end": 1487883599999,
            "startIsMilestone": false,
            "endIsMilestone": false,
            "assigs": [],
            "hasChild": false
        },
        {
            "id": "tmp_fk1486366547241",
            "name": "Разработать концепцию системы управления проектами",
            "progress": 0,
            "description": "",
            "code": "",
            "level": 2,
            "status": "STATUS_SUSPENDED",
            "depends": "4",
            "canWrite": true,
            "start": 1487883600000,
            "duration": 30,
            "end": 1491512399999,
            "startIsMilestone": false,
            "endIsMilestone": false,
            "assigs": [],
            "hasChild": false
        },
        {
            "id": "tmp_fk1486366560881",
            "name": "Утвердить на заседании Президиума ОргШтаба концепцию системы проектного управления",
            "progress": 0,
            "description": "",
            "code": "",
            "level": 2,
            "status": "STATUS_SUSPENDED",
            "depends": "5",
            "canWrite": true,
            "start": 1491512400000,
            "duration": 10,
            "end": 1492721999999,
            "startIsMilestone": false,
            "endIsMilestone": false,
            "assigs": [],
            "hasChild": false
        },
        {
            "id": "tmp_fk1486366596338",
            "name": "Разработать систему мониторинга и отчётности  (\"проектный светофор\")",
            "progress": 0,
            "description": "",
            "code": "",
            "level": 2,
            "status": "STATUS_SUSPENDED",
            "depends": "4",
            "canWrite": true,
            "start": 1487883600000,
            "duration": 44,
            "end": 1493326799999,
            "startIsMilestone": false,
            "endIsMilestone": false,
            "assigs": [],
            "hasChild": false
        },
        {
            "id": "tmp_fk1486366628103",
            "name": "Завершить разработку и утвердить необходимый пакет нормативно-правовой документации (регламенты, стандарты и пр.) и шаблоны документов по управлению проектами в ИОГВ ЛО",
            "progress": 0,
            "description": "",
            "code": "",
            "level": 2,
            "status": "STATUS_SUSPENDED",
            "depends": "7",
            "canWrite": true,
            "start": 1493326800000,
            "duration": 14,
            "end": 1495141199999,
            "startIsMilestone": false,
            "endIsMilestone": false,
            "assigs": [],
            "hasChild": false
        },
        {
            "id": "tmp_fk1486366726829",
            "name": "Подготовить пакет необходимой документации для дальнейшего внедрения информационной системы по управлению проектами",
            "progress": 0,
            "description": "",
            "code": "",
            "level": 2,
            "status": "STATUS_SUSPENDED",
            "depends": "6",
            "canWrite": true,
            "start": 1492722000000,
            "duration": 13,
            "end": 1494536399999,
            "startIsMilestone": false,
            "endIsMilestone": false,
            "assigs": [],
            "hasChild": false
        },
        {
            "id": "tmp_fk1486366765090",
            "name": "Инициация и управление пилотными проектами",
            "progress": 0,
            "description": "",
            "code": "",
            "level": 1,
            "status": "STATUS_SUSPENDED",
            "depends": "",
            "canWrite": true,
            "start": 1495141200000,
            "duration": 34,
            "end": 1499374799999,
            "startIsMilestone": false,
            "endIsMilestone": false,
            "assigs": [],
            "hasChild": true
        },
        {
            "id": "tmp_fk1486366779879",
            "name": "Сформировать реестр пилотных проектов (не менее 10 шт.) из проектов КЭРиИД",
            "progress": 0,
            "description": "",
            "code": "",
            "level": 2,
            "status": "STATUS_SUSPENDED",
            "depends": "2",
            "canWrite": true,
            "start": 1495141200000,
            "duration": 10,
            "end": 1496350799999,
            "startIsMilestone": false,
            "endIsMilestone": false,
            "assigs": [],
            "hasChild": false
        },
        {
            "id": "tmp_fk1486366786727",
            "name": "Подготовить управляющую проектную документацию по пилотным проектам (паспорт проекта, план-график проекта) в соответствии с реестром пилотных проектов и обеспечить координацию проектов силами проектного офиса",
            "progress": 0,
            "description": "",
            "code": "",
            "level": 2,
            "status": "STATUS_SUSPENDED",
            "depends": "2",
            "canWrite": true,
            "start": 1495141200000,
            "duration": 14,
            "end": 1496955599999,
            "startIsMilestone": false,
            "endIsMilestone": false,
            "assigs": [],
            "hasChild": false
        },
        {
            "id": "tmp_fk1486366792953",
            "name": "Обеспечить координацию подготовки ежемесячных отчетов («проектных светофоров») по пилотным проектам",
            "progress": 0,
            "description": "",
            "code": "",
            "level": 2,
            "status": "STATUS_SUSPENDED",
            "depends": "2",
            "canWrite": true,
            "start": 1495141200000,
            "duration": 34,
            "end": 1499374799999,
            "startIsMilestone": false,
            "endIsMilestone": false,
            "assigs": [],
            "hasChild": false
        },
        {
            "id": "tmp_fk1486366799353",
            "name": "Сформировать реестр приоритетных проектов ИОГВ ЛО",
            "progress": 0,
            "description": "",
            "code": "",
            "level": 2,
            "status": "STATUS_SUSPENDED",
            "depends": "2",
            "canWrite": true,
            "start": 1495141200000,
            "duration": 14,
            "end": 1496955599999,
            "startIsMilestone": false,
            "endIsMilestone": false,
            "assigs": [],
            "hasChild": false
        },
        {
            "id": "tmp_fk1486366807281",
            "name": "Актуализировать и утвердить дорожную карту по улучшению инвестиционного климата в ИОГВ ЛО",
            "progress": 0,
            "description": "",
            "code": "",
            "level": 2,
            "status": "STATUS_SUSPENDED",
            "depends": "14",
            "canWrite": true,
            "start": 1496955600000,
            "duration": 15,
            "end": 1498769999999,
            "startIsMilestone": false,
            "endIsMilestone": false,
            "assigs": [],
            "hasChild": false
        },
        {
            "id": "tmp_fk1486366813367",
            "name": "Орг штатные мероприятия",
            "progress": 0,
            "description": "",
            "code": "",
            "level": 1,
            "status": "STATUS_SUSPENDED",
            "depends": "",
            "canWrite": true,
            "start": 1485464400000,
            "duration": 92,
            "end": 1496955599999,
            "startIsMilestone": false,
            "endIsMilestone": false,
            "assigs": [],
            "hasChild": true
        },
        {
            "id": "tmp_fk1486366822288",
            "name": "Сформировать участников системы управления проектами (проектный офис, команды проекта)",
            "progress": 0,
            "description": "",
            "code": "",
            "level": 2,
            "status": "STATUS_SUSPENDED",
            "depends": "",
            "canWrite": true,
            "start": 1485464400000,
            "duration": 5,
            "end": 1486069199999,
            "startIsMilestone": false,
            "endIsMilestone": false,
            "assigs": [],
            "hasChild": false
        },
        {
            "id": "tmp_fk1486366827975",
            "name": "Внедрить в работу регулярные заседания Организационного Штаба",
            "progress": 0,
            "description": "",
            "code": "",
            "level": 2,
            "status": "STATUS_SUSPENDED",
            "depends": "2",
            "canWrite": true,
            "start": 1495141200000,
            "duration": 14,
            "end": 1496955599999,
            "startIsMilestone": false,
            "endIsMilestone": false,
            "assigs": [],
            "hasChild": false
        },
        {
            "id": "tmp_fk1486366831657",
            "name": "Разное",
            "progress": 0,
            "description": "",
            "code": "",
            "level": 1,
            "status": "STATUS_SUSPENDED",
            "depends": "",
            "canWrite": true,
            "start": 1485464400000,
            "duration": 98,
            "end": 1497646799999,
            "startIsMilestone": false,
            "endIsMilestone": false,
            "assigs": [],
            "hasChild": true
        },
        {
            "id": "tmp_fk1486366835975",
            "name": "Провести серию обучений по основам проектного управления для задействованных в проектах сотрудников",
            "progress": 0,
            "description": "",
            "code": "",
            "level": 2,
            "status": "STATUS_SUSPENDED",
            "depends": "2",
            "canWrite": true,
            "start": 1495141200000,
            "duration": 13,
            "end": 1496869199999,
            "startIsMilestone": false,
            "endIsMilestone": false,
            "assigs": [],
            "hasChild": false
        },
        {
            "id": "tmp_fk1486366840991",
            "name": "Сформировать пул энтузиастов, поддерживающих систему управления проектами и обеспечивающий «точку входа» в комитет для старта пилотного проекта в комитете",
            "progress": 0,
            "description": "",
            "code": "",
            "level": 2,
            "status": "STATUS_SUSPENDED",
            "depends": "2",
            "canWrite": true,
            "start": 1495141200000,
            "duration": 14,
            "end": 1496955599999,
            "startIsMilestone": false,
            "endIsMilestone": false,
            "assigs": [],
            "hasChild": false
        },
        {
            "id": "tmp_fk1486366847511",
            "name": "Разработать систему КПЭ и систему мотивации для участников проектов",
            "progress": 0,
            "description": "",
            "code": "",
            "level": 2,
            "status": "STATUS_SUSPENDED",
            "depends": "3",
            "canWrite": true,
            "start": 1487278800000,
            "duration": 13,
            "end": 1488920399999,
            "startIsMilestone": false,
            "endIsMilestone": false,
            "assigs": [],
            "hasChild": false
        },
        {
            "id": "tmp_fk1486366855864",
            "name": "Разработать GR и PR программы по информированию о результатах проекта",
            "progress": 0,
            "description": "",
            "code": "",
            "level": 2,
            "status": "STATUS_SUSPENDED",
            "depends": "2",
            "canWrite": true,
            "start": 1495141200000,
            "duration": 5,
            "end": 1495745999999,
            "startIsMilestone": false,
            "endIsMilestone": false,
            "assigs": [],
            "hasChild": false
        },
        {
            "id": "tmp_fk1486366861407",
            "name": "Обеспечить стыковку проекта со связанными проектами программы «Госуправление 2.0.»",
            "progress": 0,
            "description": "",
            "code": "",
            "level": 2,
            "status": "STATUS_SUSPENDED",
            "depends": "14",
            "canWrite": true,
            "start": 1496955600000,
            "duration": 6,
            "end": 1497646799999,
            "startIsMilestone": false,
            "endIsMilestone": false,
            "assigs": [],
            "hasChild": false
        }
    ],
    "selectedRow": 23,
    "deletedTaskIds": [],
    "resources": [
        {
            "id": "tmp_1",
            "name": "Resource 12"
        },

    ],
    "roles": [
        {
            "id": "tmp_1",
            "name": "Project Manager"
        },
    ],
    "canWrite": false,
    "canWriteOnParent": false,
    "splitterPosition": 60.05859375,
    "zoom": "s"
}