/**
 * Created by imaslov on 06.02.17.
 */
var project2 = {
    "tasks": [
        {
            "id": -1,
            "name": "ПРОЕКТ \"ЗАЙМИСЬ ДЕЛОМ!\" 1 ЭТАП",
            "progress": 0,
            "description": "",
            "code": "",
            "level": 0,
            "status": "STATUS_ACTIVE",
            "depends": "",
            "canWrite": true,
            "start": 1462309200000,
            "duration": 169,
            "end": 1483390799999,
            "startIsMilestone": false,
            "endIsMilestone": false,
            "collapsed": false,
            "assigs": [],
            "hasChild": true
        },
        {
            "id": "tmp_fk1486366951382",
            "name": "ИНИЦИИРОВАНИЕ",
            "progress": 0,
            "description": "",
            "code": "",
            "level": 1,
            "status": "STATUS_DONE",
            "depends": "",
            "canWrite": true,
            "start": 1462309200000,
            "duration": 1,
            "end": 1462395599999,
            "startIsMilestone": false,
            "endIsMilestone": false,
            "collapsed": false,
            "assigs": [],
            "hasChild": true
        },
        {
            "id": "tmp_fk1486366461612",
            "name": "Инициирование  проекта",
            "progress": 0,
            "description": "",
            "code": "",
            "level": 2,
            "status": "STATUS_DONE",
            "depends": "",
            "canWrite": true,
            "start": 1462309200000,
            "duration": 1,
            "end": 1462395599999,
            "startIsMilestone": false,
            "endIsMilestone": false,
            "assigs": [],
            "hasChild": false
        },
        {
            "id": "tmp_fk1486366512252",
            "name": "ПЛАНИРОВАНИЕ",
            "progress": 0,
            "description": "",
            "code": "",
            "level": 1,
            "status": "STATUS_DONE",
            "depends": "",
            "canWrite": true,
            "start": 1462309200000,
            "duration": 22,
            "end": 1464987599999,
            "startIsMilestone": false,
            "endIsMilestone": false,
            "collapsed": false,
            "assigs": [],
            "hasChild": true
        },
        {
            "id": "tmp_fk1486366547241",
            "name": "Подготовка паспорта проекта",
            "progress": 0,
            "description": "",
            "code": "",
            "level": 2,
            "status": "STATUS_DONE",
            "depends": "3",
            "canWrite": true,
            "start": 1462395600000,
            "duration": 9,
            "end": 1463518799999,
            "startIsMilestone": false,
            "endIsMilestone": false,
            "assigs": [],
            "hasChild": false
        },
        {
            "id": "tmp_fk1486366560881",
            "name": "Подготовка графика проекта",
            "progress": 0,
            "description": "",
            "code": "",
            "level": 2,
            "status": "STATUS_DONE",
            "depends": "3",
            "canWrite": true,
            "start": 1462395600000,
            "duration": 14,
            "end": 1464123599999,
            "startIsMilestone": false,
            "endIsMilestone": false,
            "assigs": [],
            "hasChild": false
        },
        {
            "id": "tmp_fk1486366596338",
            "name": "Утверждение паспорта и графика проекта",
            "progress": 0,
            "description": "",
            "code": "",
            "level": 2,
            "status": "STATUS_DONE",
            "depends": "5,6",
            "canWrite": true,
            "start": 1464123600000,
            "duration": 6,
            "end": 1464814799999,
            "startIsMilestone": false,
            "endIsMilestone": false,
            "assigs": [],
            "hasChild": false
        },
        {
            "id": "tmp_fk1486366628103",
            "name": "Планирование завершено",
            "progress": 0,
            "description": "",
            "code": "",
            "level": 2,
            "status": "STATUS_DONE",
            "depends": "7",
            "canWrite": true,
            "start": 1464901200000,
            "duration": 1,
            "end": 1464987599999,
            "startIsMilestone": false,
            "endIsMilestone": false,
            "assigs": [],
            "hasChild": false
        },
        {
            "id": "tmp_fk1486366726829",
            "name": "ИСПОЛНЕНИЕ",
            "progress": 0,
            "description": "",
            "code": "",
            "level": 1,
            "status": "STATUS_ACTIVE",
            "depends": "",
            "canWrite": true,
            "start": 1464901200000,
            "duration": 138,
            "end": 1481921999999,
            "startIsMilestone": false,
            "endIsMilestone": false,
            "collapsed": false,
            "assigs": [],
            "hasChild": true
        },
        {
            "id": "tmp_fk1486366765090",
            "name": "Разработка комплексой системы содействия занятости граждан",
            "progress": 0,
            "description": "",
            "code": "",
            "level": 2,
            "status": "STATUS_DONE",
            "depends": "",
            "canWrite": true,
            "start": 1464901200000,
            "duration": 54,
            "end": 1471553999999,
            "startIsMilestone": false,
            "endIsMilestone": false,
            "collapsed": false,
            "assigs": [],
            "hasChild": true
        },
        {
            "id": "tmp_fk1486366779879",
            "name": "Определение приоритетных направлений малого и среднего предпринимательства нуждающихся в поддержке.",
            "progress": 0,
            "description": "",
            "code": "",
            "level": 3,
            "status": "STATUS_DONE",
            "depends": "8",
            "canWrite": true,
            "start": 1465160400000,
            "duration": 8,
            "end": 1466024399999,
            "startIsMilestone": false,
            "endIsMilestone": false,
            "assigs": [],
            "hasChild": false
        },
        {
            "id": "tmp_fk1486366786727",
            "name": "Определение субъектов взаимодействия при организации поддержки предпринимательства в Ленинградской области.",
            "progress": 0,
            "description": "",
            "code": "",
            "level": 3,
            "status": "STATUS_DONE",
            "depends": "8",
            "canWrite": true,
            "start": 1465160400000,
            "duration": 8,
            "end": 1466024399999,
            "startIsMilestone": false,
            "endIsMilestone": false,
            "assigs": [],
            "hasChild": false
        },
        {
            "id": "tmp_fk1486366792953",
            "name": "Разработка проекта типового соглашения о взаимодействии с участниками проекта.",
            "progress": 0,
            "description": "",
            "code": "",
            "level": 3,
            "status": "STATUS_DONE",
            "depends": "12,11",
            "canWrite": true,
            "start": 1466024400000,
            "duration": 10,
            "end": 1467233999999,
            "startIsMilestone": false,
            "endIsMilestone": false,
            "assigs": [],
            "hasChild": false
        },
        {
            "id": "tmp_fk1486366799353",
            "name": "Заключение соглашения о взаимодействии с Участниками Проекта и заинтересованными структурами поддержки предпринимателей ЛО",
            "progress": 0,
            "description": "",
            "code": "",
            "level": 3,
            "status": "STATUS_DONE",
            "depends": "13",
            "canWrite": true,
            "start": 1467234000000,
            "duration": 5,
            "end": 1467838799999,
            "startIsMilestone": false,
            "endIsMilestone": false,
            "assigs": [],
            "hasChild": false
        },
        {
            "id": "tmp_fk1486366807281",
            "name": "Разработка типовой формы предоставления информации для начинающих предпринимателей.",
            "progress": 0,
            "description": "",
            "code": "",
            "level": 3,
            "status": "STATUS_DONE",
            "depends": "14",
            "canWrite": true,
            "start": 1467838800000,
            "duration": 10,
            "end": 1469048399999,
            "startIsMilestone": false,
            "endIsMilestone": false,
            "assigs": [],
            "hasChild": false
        },
        {
            "id": "tmp_fk1486366813367",
            "name": "Составление пошаговой инструкции консультационной поддержки для специалистов  ГКУ ЦЗН ЛО",
            "progress": 0,
            "description": "",
            "code": "",
            "level": 3,
            "status": "STATUS_DONE",
            "depends": "15",
            "canWrite": true,
            "start": 1469048400000,
            "duration": 10,
            "end": 1470257999999,
            "startIsMilestone": false,
            "endIsMilestone": false,
            "assigs": [],
            "hasChild": false
        },
        {
            "id": "tmp_1486381303225",
            "name": "Формирование технологической карты получения комплекса услуг",
            "progress": 0,
            "description": "",
            "code": "",
            "level": 3,
            "status": "STATUS_DONE",
            "depends": "16",
            "canWrite": true,
            "start": 1470258000000,
            "duration": 9,
            "end": 1471467599999,
            "startIsMilestone": false,
            "endIsMilestone": false,
            "assigs": [],
            "hasChild": false
        },
        {
            "id": "tmp_1486381325304",
            "name": "Комплексная система разработана",
            "progress": 0,
            "description": "",
            "code": "",
            "level": 3,
            "status": "STATUS_DONE",
            "depends": "17",
            "canWrite": true,
            "start": 1471467600000,
            "duration": 1,
            "end": 1471553999999,
            "startIsMilestone": false,
            "endIsMilestone": false,
            "assigs": [],
            "hasChild": false
        },
        {
            "id": "tmp_fk1486366831657",
            "name": "Проведение 3х однодневных обучающих семинаров по вопросам реализации комплексной системы для Участников Проекта",
            "progress": 0,
            "description": "",
            "code": "",
            "level": 2,
            "status": "STATUS_DONE",
            "depends": "18",
            "canWrite": true,
            "start": 1471554000000,
            "duration": 4,
            "end": 1472072399999,
            "startIsMilestone": false,
            "endIsMilestone": false,
            "collapsed": false,
            "assigs": [],
            "hasChild": false
        },
        {
            "id": "tmp_fk1486366835975",
            "name": "Работа по легализации незаконных предпринимателей",
            "progress": 0,
            "description": "",
            "code": "",
            "level": 2,
            "status": "STATUS_DONE",
            "depends": "",
            "canWrite": true,
            "start": 1472072400000,
            "duration": 80,
            "end": 1481921999999,
            "startIsMilestone": false,
            "endIsMilestone": false,
            "collapsed": false,
            "assigs": [],
            "hasChild": true
        },
        {
            "id": "tmp_fk1486366840991",
            "name": "Апробация  комплекса услуг по плану получения услуг.",
            "progress": 0,
            "description": "",
            "code": "",
            "level": 3,
            "status": "STATUS_DONE",
            "depends": "19",
            "canWrite": true,
            "start": 1472072400000,
            "duration": 5,
            "end": 1472677199999,
            "startIsMilestone": false,
            "endIsMilestone": false,
            "assigs": [],
            "hasChild": false
        },
        {
            "id": "tmp_fk1486366847511",
            "name": "Доработка комплекса услуг по плану получения услуг для специалистов ГКУ ЦЗН ЛО",
            "progress": 0,
            "description": "",
            "code": "",
            "level": 3,
            "status": "STATUS_DONE",
            "depends": "21",
            "canWrite": true,
            "start": 1472677200000,
            "duration": 10,
            "end": 1473886799999,
            "startIsMilestone": false,
            "endIsMilestone": false,
            "assigs": [],
            "hasChild": false
        },
        {
            "id": "tmp_fk1486366855864",
            "name": "Работа по легализации незаконных предпринимателей",
            "progress": 0,
            "description": "",
            "code": "",
            "level": 3,
            "status": "STATUS_DONE",
            "depends": "22",
            "canWrite": true,
            "start": 1473886800000,
            "duration": 65,
            "end": 1481921999999,
            "startIsMilestone": false,
            "endIsMilestone": false,
            "assigs": [],
            "hasChild": false
        },
        {
            "id": "tmp_fk1486366861407",
            "name": "Проведение мониторинга реализации Проекта.",
            "progress": 0,
            "description": "",
            "code": "",
            "level": 2,
            "status": "STATUS_DONE",
            "depends": "22",
            "canWrite": true,
            "start": 1473886800000,
            "duration": 65,
            "end": 1481921999999,
            "startIsMilestone": false,
            "endIsMilestone": false,
            "assigs": [],
            "hasChild": false
        },
        {
            "id": "tmp_fk1486381445438",
            "name": "Подготовка информационных материалов для внешнего распространения и пресс-релизов",
            "progress": 0,
            "description": "",
            "code": "",
            "level": 2,
            "status": "STATUS_ACTIVE",
            "depends": "",
            "canWrite": true,
            "start": 1471467600000,
            "duration": 85,
            "end": 1481921999999,
            "startIsMilestone": false,
            "endIsMilestone": false,
            "assigs": [],
            "hasChild": true
        },
        {
            "id": "tmp_fk1486381452617",
            "name": "Участие в тематических мероприятиях (семинары, выставки круглые столы).",
            "progress": 0,
            "description": "",
            "code": "",
            "level": 3,
            "status": "STATUS_DONE",
            "depends": "18",
            "canWrite": true,
            "start": 1471554000000,
            "duration": 84,
            "end": 1481921999999,
            "startIsMilestone": false,
            "endIsMilestone": false,
            "assigs": [],
            "hasChild": false
        },
        {
            "id": "tmp_fk1486381464887",
            "name": "Организация продвижения Проекта в сети интернет",
            "progress": 0,
            "description": "",
            "code": "",
            "level": 3,
            "status": "STATUS_ACTIVE",
            "depends": "18",
            "canWrite": true,
            "start": 1471554000000,
            "duration": 84,
            "end": 1481921999999,
            "startIsMilestone": false,
            "endIsMilestone": false,
            "assigs": [],
            "hasChild": false
        },
        {
            "id": "tmp_fk1486381487879",
            "name": "ЗАВЕРШЕНИЕ ИСПОЛНЕНИЯ",
            "progress": 0,
            "description": "",
            "code": "",
            "level": 2,
            "status": "STATUS_ACTIVE",
            "depends": "",
            "canWrite": true,
            "start": 1481835600000,
            "duration": 1,
            "end": 1481921999999,
            "startIsMilestone": false,
            "endIsMilestone": false,
            "assigs": [],
            "hasChild": false
        },
        {
            "id": "tmp_fk1486381491892",
            "name": "ЗАВЕРШЕНИЕ",
            "progress": 0,
            "description": "",
            "code": "",
            "level": 1,
            "status": "STATUS_SUSPENDED",
            "depends": "",
            "canWrite": true,
            "start": 1482094800000,
            "duration": 10,
            "end": 1483390799999,
            "startIsMilestone": false,
            "endIsMilestone": false,
            "collapsed": false,
            "assigs": [],
            "hasChild": true
        },
        {
            "id": "tmp_fk1486383271359",
            "name": "Подготовка отчета о завершении проекта",
            "progress": 0,
            "description": "",
            "code": "",
            "level": 2,
            "status": "STATUS_SUSPENDED",
            "depends": "28",
            "canWrite": true,
            "start": 1482094800000,
            "duration": 5,
            "end": 1482526799999,
            "startIsMilestone": false,
            "endIsMilestone": false,
            "assigs": [],
            "hasChild": false
        },
        {
            "id": "tmp_1486383757581",
            "name": "Подписание отчета о завершении проекта",
            "progress": 0,
            "description": "",
            "code": "",
            "level": 2,
            "status": "STATUS_SUSPENDED",
            "depends": "30",
            "canWrite": true,
            "start": 1482786000000,
            "duration": 4,
            "end": 1483131599999,
            "startIsMilestone": false,
            "endIsMilestone": false,
            "assigs": [],
            "hasChild": false
        },
        {
            "id": "tmp_1486383794528",
            "name": "Формирование извлеченных уроков по проекту",
            "progress": 0,
            "description": "",
            "code": "",
            "level": 2,
            "status": "STATUS_SUSPENDED",
            "depends": "28",
            "canWrite": true,
            "start": 1482094800000,
            "duration": 9,
            "end": 1483131599999,
            "startIsMilestone": false,
            "endIsMilestone": false,
            "assigs": [],
            "hasChild": false
        },
        {
            "id": "tmp_1486383796462",
            "name": "Архивация данных по проекту",
            "progress": 0,
            "description": "",
            "code": "",
            "level": 2,
            "status": "STATUS_SUSPENDED",
            "depends": "28",
            "canWrite": true,
            "start": 1482094800000,
            "duration": 9,
            "end": 1483131599999,
            "startIsMilestone": false,
            "endIsMilestone": false,
            "assigs": [],
            "hasChild": false
        },
        {
            "id": "tmp_1486383809187",
            "name": "ЗАВЕРШЕНИЕ ПРОЕКТА",
            "progress": 0,
            "description": "",
            "code": "",
            "level": 2,
            "status": "STATUS_SUSPENDED",
            "depends": "31,32,33",
            "canWrite": true,
            "start": 1483304400000,
            "duration": 1,
            "end": 1483390799999,
            "startIsMilestone": false,
            "endIsMilestone": false,
            "assigs": [],
            "hasChild": false
        }
    ],
    "selectedRow": 25,
    "deletedTaskIds": [],
    "resources": [
        {
            "id": "tmp_1",
            "name": "Resource 12"
        }
    ],
    "roles": [
        {
            "id": "tmp_1",
            "name": "Project Manager"
        }
    ],
    "canWrite": false,
    "canWriteOnParent": false,
    "splitterPosition": 74.07407407407408,
    "zoom": "s"
}